# Generated by Django 5.2.7 on 2025-11-08 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="El título del consejo (ej: 'Oportunidad de Ahorro en Ocio')", max_length=255)),
                ('message', models.TextField(help_text='El consejo detallado generado por el LLM')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se generó el consejo')),
                ('is_read', models.BooleanField(default=False, help_text='Indica si el usuario ya vio este consejo')),
                ('user', models.ForeignKey(help_text='Usuario al que pertenece este consejo', on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consejo Financiero',
                'verbose_name_plural': 'Consejos Financieros',
                'ordering': ['-generated_at'],
            },
        ),
    ]
