# Generated by Django 5.2.7 on 2025-10-31 12:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0003_transaction_created_by_rule'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Un nombre para que el usuario identifique la regla (ej: 'Ahorrar 20% del sueldo').", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Activa o desactiva la regla. Si está inactiva, no se ejecutará.')),
                ('trigger_transaction_type', models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Gasto')], help_text='Tipo de transacción (Ingreso/Gasto) que disparará la regla.', max_length=10)),
                ('action_type', models.CharField(choices=[('PERCENTAGE', 'Porcentaje'), ('FIXED', 'Monto Fijo')], help_text='Define si la acción moverá un monto fijo o un porcentaje.', max_length=20)),
                ('action_transaction_type', models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Gasto')], default='EXPENSE', help_text='La nueva transacción creada será un Ingreso o un Gasto.', max_length=10)),
                ('action_description', models.CharField(blank=True, help_text="Descripción para la nueva transacción (ej: 'Transferencia Ahorro').", max_length=255)),
                ('action_fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Usar si el tipo de acción es 'Monto Fijo'.", max_digits=10, null=True)),
                ('action_percentage', models.DecimalField(blank=True, decimal_places=2, help_text="Usar si el tipo de acción es 'Porcentaje' (ej: 20.5 para 20.5%).", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Cuenta a la que pertenece esta regla.', on_delete=django.db.models.deletion.CASCADE, related_name='event_rules', to='users.account')),
                ('action_destination_category', models.ForeignKey(help_text='Categoría de destino para la nueva transacción creada por esta regla.', on_delete=django.db.models.deletion.CASCADE, related_name='action_rules', to='transactions.category')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la regla.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trigger_category', models.ForeignKey(help_text='La regla se disparará cuando se cree una transacción en esta categoría.', on_delete=django.db.models.deletion.CASCADE, related_name='trigger_rules', to='transactions.category')),
            ],
            options={
                'verbose_name': 'Regla de Evento',
                'verbose_name_plural': 'Reglas de Evento',
            },
        ),
    ]
