# Generated by Django 5.2.7 on 2025-11-02 14:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('transactions', '0003_transaction_created_by_rule'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre de la regla (ej: 'Pagar Alquiler')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_day_of_month', models.PositiveIntegerField(help_text='Día del mes (1-31) en que se ejecuta la regla.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('action_type', models.CharField(choices=[('PERCENTAGE', 'Porcentaje'), ('FIXED', 'Monto Fijo')], help_text='Tipo de acción a realizar (Monto Fijo o Porcentaje).', max_length=20)),
                ('action_description', models.CharField(blank=True, help_text="Descripción para las nuevas transacciones (ej: 'Pago Alquiler').", max_length=255)),
                ('action_fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('action_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje a mover (requiere lógica de Celery para calcular el balance de la categoría origen).', max_digits=5, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_rules', to='users.account')),
                ('action_destination_category', models.ForeignKey(help_text='Categoría de destino (a dónde va el dinero).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_action_rules', to='transactions.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_rules', to=settings.AUTH_USER_MODEL)),
                ('source_category', models.ForeignKey(help_text='Categoría de origen (de dónde sale el dinero).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_source_rules', to='transactions.category')),
            ],
            options={
                'verbose_name': 'Regla Programada',
                'verbose_name_plural': 'Reglas Programadas',
                'ordering': ['schedule_day_of_month', 'name'],
            },
        ),
    ]
