# Generated by Django 5.2.7 on 2025-10-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_by_rule',
            field=models.BooleanField(default=False),
        ),
    ]
